backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
collections:
  - name: "Specials" # Used in routes, e.g., /admin/collections/blog
    label: "Specials" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "First Discounted Product", name: "first-discounted-prod", widget: "string"}
      - {label: "Percentage of Discount", name: "percentage1", widget: "number"}
      - {label: "Second Discounted Product", name: "second-discounted-prod", widget: "string"}
      - {label: "Percentage of Discount", name: "percentage2", widget: "number"}
